if(EXISTS "/root/miniob3/build_debug/unittest/log_test[1]_tests.cmake")
  include("/root/miniob3/build_debug/unittest/log_test[1]_tests.cmake")
else()
  add_test(log_test_NOT_BUILT log_test_NOT_BUILT)
endif()
