if(EXISTS "/root/miniob3/build_debug/unittest/pidfile_test[1]_tests.cmake")
  include("/root/miniob3/build_debug/unittest/pidfile_test[1]_tests.cmake")
else()
  add_test(pidfile_test_NOT_BUILT pidfile_test_NOT_BUILT)
endif()
